# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
rvm:
  - 2.2.1
osx_image: xcode8
install:
  - gem install bundler
  - bundle install
  - bundle exec pod repo update
  - bundle exec pod install
env:
  global:
    - WORKSPACE=Gorgon.xcworkspace
    - SDK=iphonesimulator
    - DESTINATION="OS=10.0,name=iPhone 6S"
    - SCHEME=Gorgon
script:
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild -workspace $WORKSPACE -scheme $SCHEME -sdk $SDK -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean test
notifications:
  email:
    on_success: never

